kind: pipeline
name: default

steps:
  - name: Construction
    image: "ubuntu:19.10"
    trigger:
      branch:
        - master
    commands:
      - "apt -y update && apt -y install git curl default-jdk"
      - "export GH_TOKEN"
      - "export FLURRY_KEY"
      - "export GH_TOKEN"
      - "export KEY_ALIAS"
      - "export KEY_PASS"
      - "export RAPID_KEY"
      - "export STORE_PASS"
      - "export TG_BOT_KEY"
      - "cd /drone/src"
      - "bash build.sh"
    environment:
      FLURRY_KEY:
        from_secret: FLURRY_KEY
      GH_TOKEN:
        from_secret: token
      KEY_ALIAS:
        from_secret: KEY_ALIAS
      KEY_PASS:
        from_secret: KEY_PASS
      RAPID_KEY:
        from_secret: RAPID_KEY
      STORE_PASS:
        from_secret: STORE_PASS
      TG_BOT_KEY:
        from_secret: TG_BOT_KEY
